apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template
  title: Python flask template
  description: Provisions a minimalistic flask application
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - description
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        description:
          title: Component description
          type: string
          description: Provide a component description
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - dev
            - stage
            - prod

  steps:
    - id: fetch-base
      name: Fetch template base to use
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}
          app_desc: ${{parameters.description}}

    - id: publish
      name: Create new Github repo
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=c2r79&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public
        defaultBranch: main

    - id: register
      name: Register new repo with Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
