apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.app_name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/los-demos/${{ values.app_name }}.git
    targetRevision: main
    path: charts/${{ values.app_name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.app_name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true