replicaCount: 2
image:
  repository: doclosjs/${{values.app_name}}
  pullPolicy: IfNotPresent
  tag: ${{values.app_name}}-${{values.app_env}}-latest
resources:
  requests:
    cpu: 50m
    memory: 50M